name = "RectifierExpectations"
uuid = "ac2a6265-0a3a-47e7-b296-cde1c0db811e"
authors = ["Nikos Gianniotis <ngiann@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
